### ISSUE TITLE
Event spreadsheet download

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/evmplus-v6#150] opened 2021-03-07 12:00 UTC
**Is your feature request related to a problem? Please describe.**
Event List may be viewed and contains limited cross-event information.  To obtain details on multiple events, it requires multiple actions.

**Describe the solution you'd like**
Implement Event List spreadsheet download with comprehensive event details.

**Comment by r-a303931** [comment] 2021-03-08 21:41
Duplicate of #131

**Closed by r-a303931** 2021-03-08 21:41 UTC
Labels: enhancement
