### ISSUE TITLE
Scan add provides unclear error messages

### ISSUE THREAD

**Issue by grioux-neo** [cap-md089/evmplus-v6#83] opened 2020-10-09 22:33 UTC
**Is your feature request related to a problem? Please describe.**
Error messages for scan add are unclear.

**Describe the solution you'd like**
Update user feedback to be more descriptive (action oriented)

**Additional context**
This is the error message when a member attempts to scan add when there is already an attendance record for that member.  Perhaps instead a message of "You're already signed up for this event" would be more informative?  Additionally, the invalid CAPID message is displayed when the text box is empty.  Considering this state is the normal in-between scan add events, is it really an error?  Perhaps removing this message if the box is blank.
![image](https://user-images.githubusercontent.com/58757358/95636512-5f2db780-0a5d-11eb-99f2-c1166562b446.png)

**Comment by r-a303931** [comment] 2020-10-09 23:53
Duplicate of #63

**Closed by r-a303931** 2020-10-09 23:53 UTC
Labels: duplicate, enhancement
